#!/bin/sh

TAG="${1:-latest}"
OPTS="${2:-}"
TIMEZONE="America/Santiago"

# build [--no-cache]
docker build $OPTS --build-arg timezone=$TIMEZONE -t npulidom/alpine-nginx-php:$TAG .
echo "\n-> Build success\n"

# image push
if [ "$#" -ne 0 ] && [ "$1" = "push" ]; then
	docker push npulidom/alpine-nginx-php:$TAG
fi
